"""Driver assistant conversation states."""


class StatesGroupMeta(type):
    pass


class StatesGroup(metaclass=StatesGroupMeta):
    pass


class State:
    def __init__(self, name: str = ""):
        self.name = name

    def __str__(self) -> str:
        return self.name or id(self)


class DriverStates(StatesGroup):
    """Driver assistant states."""

    WAIT_VEHICLE_PRESET = State("WAIT_DRIVER_VEHICLE_PRESET")
    WAIT_VEHICLE_TITLE = State("WAIT_DRIVER_VEHICLE_TITLE")
    WAIT_VEHICLE_MILEAGE = State("WAIT_DRIVER_VEHICLE_MILEAGE")
    WAIT_VEHICLE_SERVICE_KM = State("WAIT_DRIVER_VEHICLE_SERVICE_KM")
    WAIT_VEHICLE_SERVICE_MONTHS = State("WAIT_DRIVER_VEHICLE_SERVICE_MONTHS")
    WAIT_FUEL_MILEAGE = State("WAIT_DRIVER_FUEL_MILEAGE")
    WAIT_FUEL_LITERS = State("WAIT_DRIVER_FUEL_LITERS")
    WAIT_FUEL_COST = State("WAIT_DRIVER_FUEL_COST")
    WAIT_FUEL_FULL = State("WAIT_DRIVER_FUEL_FULL")
    WAIT_FUEL_STATION = State("WAIT_DRIVER_FUEL_STATION")
    WAIT_SERVICE_MILEAGE = State("WAIT_DRIVER_SERVICE_MILEAGE")
    WAIT_EXPENSE_TITLE = State("WAIT_DRIVER_EXPENSE_TITLE")
    WAIT_EXPENSE_AMOUNT = State("WAIT_DRIVER_EXPENSE_AMOUNT")
    WAIT_EXPENSE_CATEGORY = State("WAIT_DRIVER_EXPENSE_CATEGORY")
    WAIT_EXPENSE_VEHICLE = State("WAIT_DRIVER_EXPENSE_VEHICLE")
    WAIT_EXPENSE_NOTE = State("WAIT_DRIVER_EXPENSE_NOTE")
    WAIT_DOCUMENT_TITLE = State("WAIT_DRIVER_DOCUMENT_TITLE")
    WAIT_DOCUMENT_TYPE = State("WAIT_DRIVER_DOCUMENT_TYPE")
    WAIT_DOCUMENT_VEHICLE = State("WAIT_DRIVER_DOCUMENT_VEHICLE")
    WAIT_DOCUMENT_IDENTIFIER = State("WAIT_DRIVER_DOCUMENT_IDENTIFIER")
    WAIT_DOCUMENT_EXPIRES = State("WAIT_DRIVER_DOCUMENT_EXPIRES")
    WAIT_DOCUMENT_REMIND_DAYS = State("WAIT_DRIVER_DOCUMENT_REMIND_DAYS")
    WAIT_DOCUMENT_NOTE = State("WAIT_DRIVER_DOCUMENT_NOTE")
    WAIT_JOURNAL_EVENT = State("WAIT_DRIVER_JOURNAL_EVENT")
    WAIT_JOURNAL_TITLE = State("WAIT_DRIVER_JOURNAL_TITLE")
    WAIT_JOURNAL_VEHICLE = State("WAIT_DRIVER_JOURNAL_VEHICLE")
    WAIT_JOURNAL_NOTE = State("WAIT_DRIVER_JOURNAL_NOTE")
