"""
Bot keyboards package.

All keyboard factories are exported from here.
"""

from src.bot.keyboards.builder import (
    # Reply
    get_main_menu_keyboard,
    get_main_menu_inline_keyboard,
    get_cancel_keyboard,
    get_cancel_inline_keyboard,
    # Inline navigation
    get_back_inline_keyboard,
    get_home_inline_keyboard,
    get_back_home_inline_keyboard,
    # Notes
    get_notes_list_keyboard,
    get_note_view_keyboard,
    get_note_edit_keyboard,
    get_notes_archive_keyboard,
    # Lists
    get_lists_list_keyboard,
    get_list_delete_confirm_keyboard,
    get_list_item_delete_confirm_keyboard,
    get_list_member_manage_keyboard,
    get_list_members_keyboard,
    get_list_share_keyboard,
    get_list_view_keyboard,
    get_list_item_keyboard,
    get_list_items_keyboard,
    # Medications
    get_medications_list_keyboard,
    get_medication_view_keyboard,
    get_medication_edit_keyboard,
    get_medication_edit_text_keyboard,
    get_medication_edit_dosage_keyboard,
    get_medication_edit_instructions_keyboard,
    get_medication_edit_importance_keyboard,
    get_medication_delete_confirm_keyboard,
    get_medication_dosage_keyboard,
    get_medication_instructions_keyboard,
    get_medication_importance_keyboard,
    get_medication_reminder_keyboard,
    # Reminders
    get_reminders_list_keyboard,
    get_reminder_view_keyboard,
    get_reminder_date_keyboard,
    get_reminder_time_keyboard,
    get_reminder_confirm_keyboard,
    get_reminder_repeat_keyboard,
    get_reminder_edit_repeat_keyboard,
    # Driver
    get_driver_menu_keyboard,
    get_driver_section_keyboard,
    get_driver_templates_keyboard,
    get_driver_vehicles_keyboard,
    get_driver_vehicle_preset_keyboard,
    get_driver_vehicle_preset_confirm_keyboard,
    get_driver_vehicle_view_keyboard,
    get_driver_vehicle_delete_confirm_keyboard,
    get_driver_fuel_keyboard,
    get_driver_fuel_history_keyboard,
    get_driver_fuel_entry_keyboard,
    get_driver_fuel_delete_confirm_keyboard,
    get_driver_service_keyboard,
    get_driver_step_keyboard,
    get_driver_full_tank_keyboard,
    get_driver_expenses_keyboard,
    get_driver_expense_view_keyboard,
    get_driver_expense_delete_confirm_keyboard,
    get_driver_expense_category_keyboard,
    get_driver_vehicle_choice_keyboard,
    get_driver_documents_keyboard,
    get_driver_document_view_keyboard,
    get_driver_document_delete_confirm_keyboard,
    get_driver_document_type_keyboard,
    get_driver_document_remind_keyboard,
    # Settings
    get_settings_keyboard,
    get_timezone_keyboard,
    # Helpers
    parse_callback_data,
)

__all__ = [
    # Reply
    "get_main_menu_keyboard",
    "get_main_menu_inline_keyboard",
    "get_cancel_keyboard",
    "get_cancel_inline_keyboard",
    # Inline navigation
    "get_back_inline_keyboard",
    "get_home_inline_keyboard",
    "get_back_home_inline_keyboard",
    # Notes
    "get_notes_list_keyboard",
    "get_note_view_keyboard",
    "get_note_edit_keyboard",
    "get_notes_archive_keyboard",
    # Lists
    "get_lists_list_keyboard",
    "get_list_delete_confirm_keyboard",
    "get_list_item_delete_confirm_keyboard",
    "get_list_member_manage_keyboard",
    "get_list_members_keyboard",
    "get_list_share_keyboard",
    "get_list_view_keyboard",
    "get_list_item_keyboard",
    "get_list_items_keyboard",
    # Medications
    "get_medications_list_keyboard",
    "get_medication_view_keyboard",
    "get_medication_edit_keyboard",
    "get_medication_edit_text_keyboard",
    "get_medication_edit_dosage_keyboard",
    "get_medication_edit_instructions_keyboard",
    "get_medication_edit_importance_keyboard",
    "get_medication_delete_confirm_keyboard",
    "get_medication_dosage_keyboard",
    "get_medication_instructions_keyboard",
    "get_medication_importance_keyboard",
    "get_medication_reminder_keyboard",
    # Reminders
    "get_reminders_list_keyboard",
    "get_reminder_view_keyboard",
    "get_reminder_date_keyboard",
    "get_reminder_time_keyboard",
    "get_reminder_confirm_keyboard",
    "get_reminder_repeat_keyboard",
    "get_reminder_edit_repeat_keyboard",
    # Driver
    "get_driver_menu_keyboard",
    "get_driver_section_keyboard",
    "get_driver_templates_keyboard",
    "get_driver_vehicles_keyboard",
    "get_driver_vehicle_preset_keyboard",
    "get_driver_vehicle_preset_confirm_keyboard",
    "get_driver_vehicle_view_keyboard",
    "get_driver_vehicle_delete_confirm_keyboard",
    "get_driver_fuel_keyboard",
    "get_driver_fuel_history_keyboard",
    "get_driver_fuel_entry_keyboard",
    "get_driver_fuel_delete_confirm_keyboard",
    "get_driver_service_keyboard",
    "get_driver_step_keyboard",
    "get_driver_full_tank_keyboard",
    "get_driver_expenses_keyboard",
    "get_driver_expense_view_keyboard",
    "get_driver_expense_delete_confirm_keyboard",
    "get_driver_expense_category_keyboard",
    "get_driver_vehicle_choice_keyboard",
    "get_driver_documents_keyboard",
    "get_driver_document_view_keyboard",
    "get_driver_document_delete_confirm_keyboard",
    "get_driver_document_type_keyboard",
    "get_driver_document_remind_keyboard",
    # Settings
    "get_settings_keyboard",
    "get_timezone_keyboard",
    # Helpers
    "parse_callback_data",
]
